version: 2.1

orbs:
  vault: contentful/vault@1

jobs:
  build:
    docker:
      - image: node:22.16.0
    steps:
      - checkout
      - run: npm ci
      - run: NODE_ENV=production && npm run build

  release:
    docker:
      - image: node:22.16.0
    steps:
      - checkout
      - run: npm ci
      - vault/get-secrets:
          template-preset: semantic-release-ecosystem
      - run: |
          rm -f .npmrc
          echo "//npm.pkg.github.com/:_authToken=${GITHUB_PACKAGES_READ_TOKEN}" > ~/.npmrc
          echo "@contentful:registry=https://npm.pkg.github.com" >> ~/.npmrc
      - run: npm run semantic-release

workflows:
  # Build for all branches, release only for main and semver-packaging branches
  build_and_release_if_branch_is_main:
    jobs:
      - build:
          context: vault
      - release:
          filters:
            branches:
              only:
                - main
                - semver-packaging
          context: vault
          requires:
            - build
