version: 2.1

orbs:
  vault: contentful/vault@1

jobs:
  build_and_release:
    docker:
      - image: node:22.16.0
    steps:
      - checkout
      - run: npm ci
      - vault/get-secrets:
          template-preset: 'semantic-release-ecosystem'
      - run: echo "Running in Circle CI"
      - run: npm run build
